{% set name = "rabbitmq-server" %}
{% set version = "3.7.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://github.com/rabbitmq/{{ name }}/releases/download/v{{ version }}/{{ name }}-generic-unix-{{ version }}.tar.xz
  sha256: 83abd26dc2f27ea6eee85324163aecd36f1b861e58a027df83f631cbd89ead5d
  patches:
    - a2f5620.patch  # wrapper to fake RABBITMQ_HOME location
    - f52bca4.patch  # SYS_PREFIX is set to Conda's PREFIX

build:
  number: 0
  skip: True  # [win]
  no_link:
    - etc/rabbitmq
    - var/*/rabbitmq

requirements:
  build:
    - gettext

  run:
    - erlang >=20.3,<22

test:
  commands:
    - rabbitmq-server&  # [linux]
    - sleep 2  # [linux]
    - rabbitmqctl start_app  # [linux]   
    - rabbitmqctl status     # [linux]
    - rabbitmqctl stop       # [linux]

about:
  home: http://www.rabbitmq.com
  license: MPL 1.1
  license_family: OTHER
  license_file: LICENSE
  summary: Open source multi-protocol messaging broker

  description: |
    RabbitMQ is lightweight and easy to deploy on premise and in the cloud. 
    It supports multiple messaging protocols. RabbitMQ can be deployed in 
    distributed and federated configurations to meet high-scale, 
    high-availability requirements.
  doc_url: https://www.rabbitmq.com/documentation.html
  dev_url: https://github.com/rabbitmq/rabbitmq-server

extra:
  recipe-maintainers:
    - sodre
