{% set name = "rabbitmq-server" %}
{% set version = "3.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rabbitmq/{{ name }}/releases/download/v{{ version }}/{{ name }}-generic-unix-{{ version }}.tar.xz
    sha256: 4075afddaad2f6dbddbaf8aff2fe19bc95901072d8c28d0717c7482ceb695d0c
    patches:
      - f52bca4.patch  # SYS_PREFIX is set to Conda's PREFIX
    folder: src
  - path: rabbitmq-script-wrapper  # wrapper to fake RABBITMQ_HOME location

build:
  number: 0
  skip: true  # [win]
  no_link:
    - etc/rabbitmq
    - var/*/rabbitmq

requirements:
  build:
    - gettext
  run:
    - erlang >=23.3,<26
    - socat

test:
  files:
    - test-rabbitmq.sh
  commands:
    - ./test-rabbitmq.sh

about:
  home: https://www.rabbitmq.com
  license: MPL-2.0
  license_file: LICENSE
  summary: Open source multi-protocol messaging broker
  description: |
    RabbitMQ is lightweight and easy to deploy on premise and in the cloud.
    It supports multiple messaging protocols. RabbitMQ can be deployed in
    distributed and federated configurations to meet high-scale,
    high-availability requirements.
  doc_url: https://www.rabbitmq.com/documentation.html
  dev_url: https://github.com/rabbitmq/rabbitmq-server

extra:
  recipe-maintainers:
    - rjgildea
    - anthchirp
    - sodre
