{% set name = "rabbitmq-server" %}
{% set version = "4.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rabbitmq/{{ name }}/releases/download/v{{ version }}/{{ name }}-generic-unix-{{ version }}.tar.xz
    sha256: f85df3588a82cf212883fdd1b3d2b3f9be281e9269e8c0195086f1572432ed1f
    patches:
      - f52bca4.patch  # SYS_PREFIX is set to Conda's PREFIX
    folder: src
  - path: rabbitmq-script-wrapper  # wrapper to fake RABBITMQ_HOME location

build:
  number: 0
  skip: true  # [win]
  no_link:
    - etc/rabbitmq
    - var/*/rabbitmq

requirements:
  build:
    - gettext
  run:
    - erlang >=26.2,<=27.2
    - socat

test:
  files:
    - test-rabbitmq.sh
  commands:
    - ./test-rabbitmq.sh

about:
  home: https://www.rabbitmq.com
  license: MPL-2.0
  license_file:
    - src/LICENSE
    - src/LICENSE-APACHE2
    - src/LICENSE-MPL-RabbitMQ
  summary: Open source multi-protocol messaging broker
  description: |
    RabbitMQ is lightweight and easy to deploy on premise and in the cloud.
    It supports multiple messaging protocols. RabbitMQ can be deployed in
    distributed and federated configurations to meet high-scale,
    high-availability requirements.
  doc_url: https://www.rabbitmq.com/documentation.html
  dev_url: https://github.com/rabbitmq/rabbitmq-server

extra:
  recipe-maintainers:
    - danielhollas
    - ndevenish
    - rjgildea
    - anthchirp
    - sodre
